In [1]:
# imports

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn

pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [6]:
path = './data/'
csv_path = path + 'to_input_openfoodfacts.csv'
sm_df = pd.read_csv(csv_path, low_memory=False)

In [7]:
import numpy as np
from sklearn.impute import SimpleImputer

In [8]:
sm_df.head()

,product_name,pnns_groups_1,pnns_groups_2,code,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
0,jeunes pousses,unknown,unknown,00000000000000225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,L.casei,unknown,unknown,00000000000003429145,NaN,1.4,0.9,9.8,9.80,2.7,0.1,0.04
2,Cacao,unknown,unknown,0000000000031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Filetes de pollo empanado,unknown,unknown,000000000003327986,163.9,1.9,1.0,NaN,NaN,15.3,1.1,0.44
4,Burger Meat Pollo,unknown,unknown,000000000004128579,194.0,11.0,3.9,5.7,0.05,18.0,NaN,NaN

In [9]:
main_cats = sm_df['pnns_groups_1'].unique()
main_cats

array(['unknown', 'Fat and sauces', 'Composite foods', 'Sugary snacks',
       'Fruits and vegetables', 'Fish Meat Eggs', 'Beverages',
       'Milk and dairy products', 'Cereals and potatoes', 'Salty snacks',
       'Alcoholic beverages', nan, 'sugary-snacks'], dtype=object)

In [10]:
sm_df['pnns_groups_1'].value_counts()

unknown                    1166781
Fish Meat Eggs              114618
Milk and dairy products     100917
Cereals and potatoes         78293
Beverages                    70328
Fat and sauces               63673
Composite foods              58221
Fruits and vegetables        55942
Sugary snacks                47312
Salty snacks                 28204
Alcoholic beverages          20093
sugary-snacks                    2
Name: pnns_groups_1, dtype: int64

In [11]:
sm_df['pnns_groups_1'].value_counts()

unknown                    1166781
Fish Meat Eggs              114618
Milk and dairy products     100917
Cereals and potatoes         78293
Beverages                    70328
Fat and sauces               63673
Composite foods              58221
Fruits and vegetables        55942
Sugary snacks                47312
Salty snacks                 28204
Alcoholic beverages          20093
sugary-snacks                    2
Name: pnns_groups_1, dtype: int64

In [12]:
all_cols = sm_df['pnns_groups_1'].unique().tolist()
all_cols

['unknown',
 'Fat and sauces',
 'Composite foods',
 'Sugary snacks',
 'Fruits and vegetables',
 'Fish Meat Eggs',
 'Beverages',
 'Milk and dairy products',
 'Cereals and potatoes',
 'Salty snacks',
 'Alcoholic beverages',
 nan,
 'sugary-snacks']

In [13]:
sm_df.columns

Index(['product_name', 'pnns_groups_1', 'pnns_groups_2', 'code',
       'energy-kcal_100g', 'fat_100g', 'saturated-fat_100g',
       'carbohydrates_100g', 'sugars_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g'],
      dtype='object')

In [14]:
main_cats = ['fat_100g', 'salt_100g']
complementary_cats = ['saturated-fat_100g','sodium_100g']

In [15]:
final_cats = [c for c in all_cols if c not in main_cats+complementary_cats]
final_cats

['unknown',
 'Fat and sauces',
 'Composite foods',
 'Sugary snacks',
 'Fruits and vegetables',
 'Fish Meat Eggs',
 'Beverages',
 'Milk and dairy products',
 'Cereals and potatoes',
 'Salty snacks',
 'Alcoholic beverages',
 nan,
 'sugary-snacks']

In [16]:
#groupby pnns_groups_1, mean, remplir avec mean / categorie
#list1 = ["fat_100g", "salt_100g"]
main_cats

['fat_100g', 'salt_100g']

In [17]:
main_cats_grp = main_cats.append('pnns_group_1')
main_cats_grp

In [39]:
main_cats_grp = ['fat_100g', 'salt_100g', 'pnns_group_1']
main_cats_grp

['fat_100g', 'salt_100g', 'pnns_group_1']

In [36]:
# sm_df[[c for c in df.columns if c in main_cats]].head()

In [41]:
sm_df.filter(main_cats).head()

   fat_100g  salt_100g
0       NaN        NaN
1       1.4        0.1
2       NaN        NaN
3       1.9        1.1
4      11.0        NaN

In [44]:
sm_df.filter(main_cats_grp).head()

TypeError: 'list' object is not callable

In [19]:
### appliquer imputer différentes strategies (check distribution) avec un groupby categories
### iterative imputer / estimation du choix d'imputer selon la distribution (mean/median/most frequent...)

In [ ]:
imp_med = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')