# imports

In [1]:
# imports

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn

pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [2]:
imp_med = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [3]:
path = './data/'
csv_path = path + 'to_input_openfoodfacts.csv'
sm_df = pd.read_csv(csv_path, low_memory=False)

# Inputing

In [4]:
### appliquer imputer différentes strategies (check distribution) avec un groupby categories
### iterative imputer / estimation du choix d'imputer selon la distribution (mean/median/most frequent...)

In [5]:
sm_df.head()

,product_name,pnns_groups_1,pnns_groups_2,code,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
0,jeunes pousses,unknown,unknown,00000000000000225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,L.casei,unknown,unknown,00000000000003429145,NaN,1.4,0.9,9.8,9.80,2.7,0.1,0.04
2,Cacao,unknown,unknown,0000000000031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Filetes de pollo empanado,unknown,unknown,000000000003327986,163.9,1.9,1.0,NaN,NaN,15.3,1.1,0.44
4,Burger Meat Pollo,unknown,unknown,000000000004128579,194.0,11.0,3.9,5.7,0.05,18.0,NaN,NaN

In [6]:
main_cats = sm_df['pnns_groups_1'].unique()
main_cats

array(['unknown', 'Fat and sauces', 'Composite foods', 'Sugary snacks',
       'Fruits and vegetables', 'Fish Meat Eggs', 'Beverages',
       'Milk and dairy products', 'Cereals and potatoes', 'Salty snacks',
       'Alcoholic beverages', nan, 'sugary-snacks'], dtype=object)

In [7]:
sm_df['pnns_groups_1'].value_counts()

unknown                    1080315
Fish Meat Eggs              113360
Milk and dairy products      99555
Cereals and potatoes         76949
Beverages                    69498
Fat and sauces               63039
Composite foods              57270
Fruits and vegetables        55230
Sugary snacks                45899
Salty snacks                 27700
Alcoholic beverages          19210
sugary-snacks                    2
Name: pnns_groups_1, dtype: int64

In [8]:
all_cats = sm_df['pnns_groups_1'].unique().tolist()
all_cats

['unknown',
 'Fat and sauces',
 'Composite foods',
 'Sugary snacks',
 'Fruits and vegetables',
 'Fish Meat Eggs',
 'Beverages',
 'Milk and dairy products',
 'Cereals and potatoes',
 'Salty snacks',
 'Alcoholic beverages',
 nan,
 'sugary-snacks']

In [9]:
all_cols = sm_df.columns
all_cols

Index(['product_name', 'pnns_groups_1', 'pnns_groups_2', 'code',
       'energy-kcal_100g', 'fat_100g', 'saturated-fat_100g',
       'carbohydrates_100g', 'sugars_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g'],
      dtype='object')

In [10]:
main_cats = ['fat_100g', 'salt_100g']
complementary_cats = ['saturated-fat_100g','sodium_100g']

In [11]:
final_cats = [c for c in all_cols if c not in main_cats+complementary_cats]
final_cats

['product_name',
 'pnns_groups_1',
 'pnns_groups_2',
 'code',
 'energy-kcal_100g',
 'carbohydrates_100g',
 'sugars_100g',
 'proteins_100g']

In [12]:
all_cols

Index(['product_name', 'pnns_groups_1', 'pnns_groups_2', 'code',
       'energy-kcal_100g', 'fat_100g', 'saturated-fat_100g',
       'carbohydrates_100g', 'sugars_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g'],
      dtype='object')

## main_cats : fat / salt => mean input

In [13]:
#groupby pnns_groups_1, mean, remplir avec mean / categorie
#list1 = ["fat_100g", "salt_100g"]
main_cats

['fat_100g', 'salt_100g']

In [14]:
#main_cats_grp = main_cats.append('pnns_group_1')
#main_cats_grp

In [15]:
#main_cats_grp = ['fat_100g', 'salt_100g', 'pnns_group_1']
#main_cats_grp

In [16]:
# sm_df[[c for c in df.columns if c in main_cats]].head()

In [17]:
sm_df.filter(main_cats).head()

   fat_100g  salt_100g
0       NaN        NaN
1       1.4        0.1
2       NaN        NaN
3       1.9        1.1
4      11.0        NaN

In [18]:
sm_df_groupby = sm_df.groupby(by='pnns_groups_1')

In [19]:
sm_df_groupby.mean()

,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
pnns_groups_1,,,,,,,,
Alcoholic beverages,66.619878,1.290206,0.267635,7.864081,3.626928,1.400195,0.469999,0.215946
Beverages,48.412283,0.820464,0.429246,8.329317,7.094946,0.954389,0.206885,0.092242
Cereals and potatoes,294.311534,4.684030,1.020387,51.001032,3.002433,10.050230,0.682527,0.274646
Composite foods,177.046995,7.539578,2.491210,18.182893,2.565496,7.652201,1.180105,0.473079
Fat and sauces,228.787619,16.480630,4.785741,10.546215,7.180036,1.967222,2.017257,0.811976
Fish Meat Eggs,207.257507,12.748846,4.186412,2.691659,0.896183,18.925177,1.933769,0.776386
Fruits and vegetables,71.978922,1.486411,0.331087,11.226577,6.711564,2.065463,0.515616,0.208700
Milk and dairy products,223.447365,15.633708,10.129301,7.687872,5.959879,12.292904,0.873741,0.363899
Salty snacks,379.848515,29.337939,6.329597,18.591729,1.903797,8.434855,1.660792,0.667126
Sugary snacks,274.965828,7.797832,3.198125,42.446313,19.491716,3.891545,0.483837,0.197936
sugary-snacks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,201.681150,9.471510,3.250305,18.148168,4.863237,9.365741,1.386422,0.588584

In [20]:
sm_df.columns

Index(['product_name', 'pnns_groups_1', 'pnns_groups_2', 'code',
       'energy-kcal_100g', 'fat_100g', 'saturated-fat_100g',
       'carbohydrates_100g', 'sugars_100g', 'proteins_100g', 'salt_100g',
       'sodium_100g'],
      dtype='object')

In [21]:
sm_df_groupby[main_cats].mean()

                          fat_100g  salt_100g
pnns_groups_1
Alcoholic beverages       1.290206   0.469999
Beverages                 0.820464   0.206885
Cereals and potatoes      4.684030   0.682527
Composite foods           7.539578   1.180105
Fat and sauces           16.480630   2.017257
Fish Meat Eggs           12.748846   1.933769
Fruits and vegetables     1.486411   0.515616
Milk and dairy products  15.633708   0.873741
Salty snacks             29.337939   1.660792
Sugary snacks             7.797832   0.483837
sugary-snacks                  NaN        NaN
unknown                   9.471510   1.386422

In [22]:
sm_df_groupby[main_cats].count()

                         fat_100g  salt_100g
pnns_groups_1
Alcoholic beverages          2135       2870
Beverages                   61924      60627
Cereals and potatoes        70277      66612
Composite foods             54068      53594
Fat and sauces              50769      56050
Fish Meat Eggs              97356      96129
Fruits and vegetables       43813      42598
Milk and dairy products     92412      89970
Salty snacks                24609      24241
Sugary snacks               29261      28303
sugary-snacks                   0          0
unknown                    774415     683831

In [23]:
# https://pandas.pydata.org/docs/user_guide/groupby.html

sm_df[main_cats] = sm_df_groupby[main_cats].transform(lambda x: x.fillna(x.mean()))

In [24]:
sm_df.isna().sum()

product_name               0
pnns_groups_1              3
pnns_groups_2              1
code                       0
energy-kcal_100g      434849
fat_100g                   5
saturated-fat_100g    431520
carbohydrates_100g    406068
sugars_100g           416361
proteins_100g         395893
salt_100g                  5
sodium_100g           502615
dtype: int64

In [54]:
sm_df_gr_transf = sm_df_groupby[main_cats].transform(lambda x: x.fillna(x.mean()))
sm_df_gr_transf

         fat_100g  salt_100g
0         9.47151   1.386422
1         1.40000   0.100000
2         9.47151   1.386422
3         1.90000   1.100000
4        11.00000   1.386422
...           ...        ...
1708025  12.00000   1.000000
1708026   9.47151   1.386422
1708027   9.47151   1.386422
1708028   0.30000   0.640000
1708029   9.47151   1.386422

[1708027 rows x 2 columns]

In [ ]:
grouped.transform(lambda x: x.fillna(inplace=False))

In [44]:
sm_df.isna().sum()

product_name               0
pnns_groups_1              3
pnns_groups_2              1
code                       0
energy-kcal_100g      434849
fat_100g              406991
saturated-fat_100g    431520
carbohydrates_100g    406068
sugars_100g           416361
proteins_100g         395893
salt_100g             503205
sodium_100g           502615
dtype: int64

In [57]:
sm_df_groupby[main_cats]

In [21]:
## faire fonction et apply par ligne ou boucler sur données uniques

In [61]:
sm_df_main_mean = sm_df_groupby[main_cats].mean()
sm_df_main_mean

                          fat_100g  salt_100g
pnns_groups_1
Alcoholic beverages       1.290206   0.469999
Beverages                 0.820464   0.206885
Cereals and potatoes      4.684030   0.682527
Composite foods           7.539578   1.180105
Fat and sauces           16.480630   2.017257
Fish Meat Eggs           12.748846   1.933769
Fruits and vegetables     1.486411   0.515616
Milk and dairy products  15.633708   0.873741
Salty snacks             29.337939   1.660792
Sugary snacks             7.797832   0.483837
sugary-snacks                  NaN        NaN
unknown                   9.471510   1.386422

In [59]:
sm_df.head()

,product_name,pnns_groups_1,pnns_groups_2,code,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,salt_100g,sodium_100g
0,jeunes pousses,unknown,unknown,00000000000000225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,L.casei,unknown,unknown,00000000000003429145,NaN,1.4,0.9,9.8,9.80,2.7,0.1,0.04
2,Cacao,unknown,unknown,0000000000031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Filetes de pollo empanado,unknown,unknown,000000000003327986,163.9,1.9,1.0,NaN,NaN,15.3,1.1,0.44
4,Burger Meat Pollo,unknown,unknown,000000000004128579,194.0,11.0,3.9,5.7,0.05,18.0,NaN,NaN

In [66]:
sm_df_main_mean['fat_100g']

pnns_groups_1
Alcoholic beverages         1.290206
Beverages                   0.820464
Cereals and potatoes        4.684030
Composite foods             7.539578
Fat and sauces             16.480630
Fish Meat Eggs             12.748846
Fruits and vegetables       1.486411
Milk and dairy products    15.633708
Salty snacks               29.337939
Sugary snacks               7.797832
sugary-snacks                    NaN
unknown                     9.471510
Name: fat_100g, dtype: float64

In [78]:
import math

def fill_grp_fat(row):
    if math.isnan(row['fat_100g']):
        cat = row['pnns_groups_1']
        print(cat)
        return sm_df_main_mean['fat_100g'][cat]
    else:
        return row['fat_100g']

In [81]:
#sm_df['pnns_groups_1'].value_counts()

In [79]:
sm_df['fat_100g'] = sm_df.apply(lambda x : fill_grp_fat(x), axis=1)

unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Milk and dairy products
Sugary snacks
unknown
unknown
Fish Meat Eggs
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Sugary snacks
unknown
Salty snacks
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Alcoholic beverages
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fruits and vegetables
unknown
unknown
Beverages
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fruits and vegetables
unknown
Milk and dairy products
Sugary snacks
Sugary snacks
Sugary snacks
unknown
unknown
Cereals and potatoes
Sugary snacks
unknown
Fish Meat Eggs
unknown
unknown
unknown
Milk and dairy products
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Milk and dairy products
Sugary snacks
unknown
Fish Meat Eggs
unknown
Sugary snacks
unknown
Fish Meat Eggs
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Sugary snacks
unknown
Sugary snacks
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Composite foods
Cereals and potatoes
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
unknown
Fish Meat Eggs
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
Sugary snacks
Sugary snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
Beverages
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Beverages
Cereals and potatoes
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
Fish Meat Eggs
Salty snacks
unknown
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
unknown
Salty snacks
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
Salty snacks
unknown
unknown
Salty snacks
unknown
Salty snacks
Salty snacks
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Milk and dairy products
unknown
unknown
unknown
Fruits and vegetables
unknown
Milk and dairy products
unknown
unknown
unknown
Cereals and potatoes
Milk and dairy products
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Cereals and potatoes
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
Sugary snacks
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Fish Meat Eggs
Cereals and potatoes
unknown
unknown
unknown
Fish Meat Eggs
unknown
Cereals and potatoes
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Sugary snacks
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
Alcoholic beverages
unknown
Alcoholic beverages
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Cereals and potatoes
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Fish Meat Eggs
unknown
Sugary snacks
unknown
Cereals and potatoes
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Beverages
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
Beverages
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
Sugary snacks
unknown
Cereals and potatoes
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
Sugary snacks
unknown
Cereals and potatoes
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
Composite foods
Composite foods
Composite foods
Composite foods
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
Cereals and potatoes
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Sugary snacks
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Beverages
unknown
unknown
Alcoholic beverages
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Composite foods
unknown
unknown
Milk and dairy products
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
Composite foods
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fruits and vegetables
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Cereals and potatoes
unknown
Fish Meat Eggs
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Sugary snacks
unknown
unknown
Beverages
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown

unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
Beverages
unknown
Fat and sauces
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Sugary snacks
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Milk and dairy products
unknown
Fat and sauces
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
unknown
Alcoholic beverages
Alcoholic beverages
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fat and sauces
unknown
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Alcoholic beverages
unknown
unknown
Sugary snacks
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Fruits and vegetables
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
Beverages
unknown
Alcoholic beverages
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Salty snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fish Meat Eggs
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Beverages
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
Composite foods
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Fat and sauces
unknown
Milk and dairy products
Fish Meat Eggs
unknown
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Cereals and potatoes
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown

unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
Sugary snacks
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Beverages
Fruits and vegetables
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
Milk and dairy products
Milk and dairy products
Milk and dairy products
Milk and dairy products
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Cereals and potatoes
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Alcoholic beverages
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
unknown
Beverages
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fish Meat Eggs
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fat and sauces
Alcoholic beverages
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
unknown
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Fat and sauces
Composite foods
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fat and sauces
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Cereals and potatoes
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fish Meat Eggs
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown

unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Cereals and potatoes
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
Fruits and vegetables
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Beverages
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Sugary snacks
Fish Meat Eggs
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Salty snacks
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
Beverages
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Cereals and potatoes
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
Cereals and potatoes
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Alcoholic beverages
unknown
unknown
unknown
Beverages
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fat and sauces
Beverages
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Sugary snacks
unknown
unknown
unknown
Fat and sauces
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fat and sauces
Sugary snacks
unknown
Composite foods
unknown
Alcoholic beverages
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Cereals and potatoes
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown

unknown
unknown
unknown
unknown
unknown
Fat and sauces
Sugary snacks
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
Salty snacks
unknown
unknown
unknown
unknown
Salty snacks
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
Salty snacks
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Salty snacks
Salty snacks
unknown
unknown
unknown
unknown
unknown
Salty snacks
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fruits and vegetables
unknown
Fruits and vegetables
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fruits and vegetables
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Composite foods
Salty snacks
unknown
unknown
Sugary snacks
unknown
unknown
Fish Meat Eggs
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
Cereals and potatoes
Composite foods
Salty snacks
Sugary snacks
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Sugary snacks
unknown
Sugary snacks
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Alcoholic beverages
Alcoholic beverages
Sugary snacks
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Composite foods
Composite foods
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Alcoholic beverages
Alcoholic beverages
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
Composite foods
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Beverages
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Beverages
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Cereals and potatoes
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fish Meat Eggs
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown

unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Composite foods
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fish Meat Eggs
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Salty snacks
Salty snacks
unknown
Sugary snacks
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Salty snacks
Salty snacks
Salty snacks
unknown
Salty snacks
Salty snacks
unknown
Fruits and vegetables
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fat and sauces
Fish Meat Eggs
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Fish Meat Eggs
Salty snacks
Sugary snacks
unknown
Alcoholic beverages
Alcoholic beverages
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fruits and vegetables
unknown
unknown
Sugary snacks
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Composite foods
unknown
unknown
Composite foods
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Beverages
unknown

unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fat and sauces
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
Cereals and potatoes
Sugary snacks
unknown
unknown
Sugary snacks
Cereals and potatoes
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
unknown
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Composite foods
unknown
Sugary snacks
Cereals and potatoes
Cereals and potatoes
Sugary snacks
Cereals and potatoes
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
unknown
Sugary snacks
Sugary snacks
Cereals and potatoes
Cereals and potatoes
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
unknown
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Sugary snacks
Cereals and potatoes
Sugary snacks
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Composite foods
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
Sugary snacks
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
Beverages
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Sugary snacks
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
Sugary snacks
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Beverages
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown

unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Fruits and vegetables
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Fish Meat Eggs
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Sugary snacks
unknown
Cereals and potatoes
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Cereals and potatoes
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fish Meat Eggs
Fruits and vegetables
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Milk and dairy products
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Salty snacks
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Beverages
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
Beverages
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
Sugary snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
Cereals and potatoes
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Salty snacks
Salty snacks
unknown
Fat and sauces
unknown
unknown
unknown
Fruits and vegetables
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Sugary snacks
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
Fruits and vegetables
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Beverages
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
Fat and sauces
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Composite foods
Sugary snacks
unknown
unknown
Fish Meat Eggs
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fruits and vegetables
Cereals and potatoes
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fruits and vegetables
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Sugary snacks
unknown
unknown
Sugary snacks
Sugary snacks
Sugary snacks
unknown
unknown
Sugary snacks
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Milk and dairy products
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Cereals and potatoes
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Cereals and potatoes
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fruits and vegetables
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Cereals and potatoes
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
Beverages
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Cereals and potatoes
Fat and sauces
Cereals and potatoes
Fat and sauces
unknown
Fat and sauces
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fat and sauces
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown

unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
Beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Fat and sauces
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fruits and vegetables
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Sugary snacks
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fruits and vegetables
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Cereals and potatoes
Fat and sauces
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fat and sauces
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
Composite foods
unknown
Beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
Beverages
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown

unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Cereals and potatoes
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
Alcoholic beverages
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Milk and dairy products
Cereals and potatoes
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
Alcoholic beverages
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
Fish Meat Eggs
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Milk and dairy products
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fat and sauces
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
Fat and sauces
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown

unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Sugary snacks
unknown
unknown
Milk and dairy products
Composite foods
unknown
unknown
Fish Meat Eggs
Composite foods
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Fat and sauces
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
Beverages
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Fat and sauces
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Beverages
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Milk and dairy products
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Sugary snacks
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Fruits and vegetables
unknown
unknown
Sugary snacks
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Composite foods
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
Fruits and vegetables
Cereals and potatoes
Fat and sauces
unknown
unknown
unknown
Composite foods
unknown
Composite foods
Composite foods
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown

unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Composite foods
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Fat and sauces
Fat and sauces
Composite foods
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Sugary snacks
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
Alcoholic beverages
unknown
Beverages
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Cereals and potatoes
unknown
unknown
Fat and sauces
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
Fruits and vegetables
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Fat and sauces
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
Sugary snacks
Beverages
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Salty snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Salty snacks
Salty snacks
unknown
Salty snacks
Salty snacks
Sugary snacks
unknown
unknown
unknown
Composite foods
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Fruits and vegetables
unknown
unknown
unknown
Composite foods
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
Milk and dairy products
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Cereals and potatoes
Fat and sauces
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fruits and vegetables
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown

unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Alcoholic beverages
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Cereals and potatoes
Cereals and potatoes
unknown
Fat and sauces
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
Milk and dairy products
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Milk and dairy products
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
Beverages
Sugary snacks
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Cereals and potatoes
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
Salty snacks
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
Alcoholic beverages
unknown
unknown
Fish Meat Eggs
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Salty snacks
Milk and dairy products
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Fat and sauces
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
Fat and sauces
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
Beverages
unknown
Sugary snacks
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
Fat and sauces
unknown
Salty snacks
unknown
Fish Meat Eggs
unknown
unknown
Milk and dairy products
Milk and dairy products
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
unknown
unknown
Beverages
unknown
Beverages
Beverages
Beverages
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
Fruits and vegetables
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
Cereals and potatoes
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
Fish Meat Eggs
unknown
Beverages
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
Fruits and vegetables
unknown
Beverages
unknown

unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
Sugary snacks
unknown
unknown
unknown
Fat and sauces
unknown
Fruits and vegetables
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
Beverages
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
Fat and sauces
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
Fat and sauces
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Fat and sauces
Alcoholic beverages
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
Milk and dairy products
Composite foods
unknown
unknown
unknown
Composite foods
unknown
unknown
Composite foods
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Composite foods
unknown
unknown
unknown
unknown
Fat and sauces
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Beverages
Beverages
Beverages
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Salty snacks
unknown
unknown
Cereals and potatoes
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
Fish Meat Eggs
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Milk and dairy products
unknown
Milk and dairy products
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
Fat and sauces
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fat and sauces
unknown
Fat and sauces
Fat and sauces
unknown
unknown
unknown
Cereals and potatoes
unknown
Beverages
Beverages
Beverages
unknown
unknown
Beverages
unknown
Beverages
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
Sugary snacks
Sugary snacks
unknown
unknown
unknown
unknown
unknown
Alcoholic beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fruits and vegetables
unknown
unknown
Beverages
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Fat and sauces
Sugary snacks
Fat and sauces
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
unknown
Cereals and potatoes
Fat and sauces
Fat and sauces
Fat and sauces
Cereals and potatoes
unknown
Fruits and vegetables
unknown
unknown
unknown
unknown
Composite foods
Composite foods
Composite foods
unknown
unknown
unknown
unknown
unknown
unknown
Sugary snacks
unknown
unknown
unknown
nan

KeyError: nan

In [22]:
## utiliser index (str) de sm_df_groupby

In [23]:
#sm_df.filter(main_cats_grp).head()

## compl_cats : sat_fat / sodium => linearRegression

In [24]:
# IterativeImputer avec estimator=LinearRegression()
#list2 = ["saturated-fat_100g", "sodium_100g"] 
complementary_cats

['saturated-fat_100g', 'sodium_100g']

In [25]:
sm_df.filter(complementary_cats).head()

   saturated-fat_100g  sodium_100g
0                 NaN          NaN
1                 0.9         0.04
2                 NaN          NaN
3                 1.0         0.44
4                 3.9          NaN

In [26]:
#sm_df_groupby.median().columns

In [27]:
#sm_df_groupby.median()

In [31]:
sm_df_groupby[complementary_cats].median()

                         saturated-fat_100g  sodium_100g
pnns_groups_1
Alcoholic beverages                    0.00     0.000000
Beverages                              0.00     0.004000
Cereals and potatoes                   0.40     0.180000
Composite foods                        1.79     0.390000
Fat and sauces                         1.10     0.520000
Fish Meat Eggs                         2.68     0.640000
Fruits and vegetables                  0.00     0.066040
Milk and dairy products                8.47     0.140000
Salty snacks                           3.50     0.520000
Sugary snacks                          0.90     0.050000
sugary-snacks                           NaN          NaN
unknown                                1.00     0.286512

## final_cats =>

In [29]:
final_cats

['product_name',
 'pnns_groups_1',
 'pnns_groups_2',
 'code',
 'energy-kcal_100g',
 'carbohydrates_100g',
 'sugars_100g',
 'proteins_100g']

In [30]:
#Reste des variables contenant des valeurs vides (sans list1, list2,  pnns_groups_1, pnns_groups_2) : 
# remplir soit avec la moyenne soit avec la mediane, en fonction de la distribution 
#- remplir avec la valeur la plus fréquente

In [ ]:
#imp_med = SimpleImputer(missing_values=np.nan, strategy='median')

###sm_df[all_num_cols] = imp_med.fit_transform(sm_df[all_num_cols])