# Data Preparation

In [1]:
# "magic commands" to enable autoreload of imported packages
%load_ext autoreload
%autoreload 2

In [2]:
# Check current working directory using `os.getcwd()` below 
import os
os.getcwd()

'/home/mijka/code/openclassrooms/projets/projet_5'

In [16]:
ls data/csv

olist_customers_dataset.csv       olist_orders_dataset.csv
olist_geolocation_dataset.csv     olist_products_dataset.csv
olist_order_items_dataset.csv     olist_sellers_dataset.csv
olist_order_payments_dataset.csv  product_category_name_translation.csv
olist_order_reviews_dataset.csv

In [4]:
pwd

'/home/mijka/code/openclassrooms/projets/projet_5'

In [14]:
csv_path = 'data/csv/'

In [15]:
# Test your code below
import pandas as pd
pd.read_csv(os.path.join(csv_path, 'olist_sellers_dataset.csv')).head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

### 2. Create the list `file_names` containing all csv file names in the csv directory

- It should look like this `file_names = ['olist_sellers_dataset.csv', ....]`
- You can use `os.listdir()`
- Make sure it only lists csv files!

In [17]:
file_names = [x for x in os.listdir(csv_path) if ".csv" in x]
file_names

['olist_customers_dataset.csv',
 'olist_products_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_geolocation_dataset.csv',
 'product_category_name_translation.csv',
 'olist_order_items_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_sellers_dataset.csv']

### 3.  Create the list of dict key `key_names` 
Starting from file_names and:
- Removing its suffix ".csv" when it exists
- Removing its suffix "_dataset.csv" when it exists
- Removing its prefix "olist_" when it exists

<details>
    <summary>Hint</summary>

- `.replace()`
    
- `str` ings are iterables you can slice with [ ]
</details>

In [18]:
file_names = [x.removesuffix('.csv') for x in file_names]
file_names = [x.removesuffix('_dataset') for x in file_names]
file_names = [x.removeprefix('olist_') for x in file_names]
file_names

['customers',
 'products',
 'order_payments',
 'geolocation',
 'product_category_name_translation',
 'order_items',
 'orders',
 'order_reviews',
 'sellers']

### 4. Construct the dictionary `data`

```python
data = { 
    'sellers': DataFrame1,
    'orders': DataFrame2,
    'order_items': DataFrame3,
    ...
    }
```

<details>
    <summary>Hint</summary>

The `zip()` method is very useful to iterate over two lists
```python
for (x, y) in zip(['a','b','c'], [1,2,3]):
    print(x,y)

# returns ('a', 1), ('b', 2), ('c', 3)
    
```
</details>

In [19]:
dataframes_list = [f'DataFrame{i}' for i, item in enumerate(file_names, start=1)]
dataframes_list

['DataFrame1',
 'DataFrame2',
 'DataFrame3',
 'DataFrame4',
 'DataFrame5',
 'DataFrame6',
 'DataFrame7',
 'DataFrame8',
 'DataFrame9']

In [20]:
data = dict(zip(file_names, dataframes_list))
data

{'customers': 'DataFrame1',
 'products': 'DataFrame2',
 'order_payments': 'DataFrame3',
 'geolocation': 'DataFrame4',
 'product_category_name_translation': 'DataFrame5',
 'order_items': 'DataFrame6',
 'orders': 'DataFrame7',
 'order_reviews': 'DataFrame8',
 'sellers': 'DataFrame9'}

In [21]:
data['customers'] = 'test'
data

{'customers': 'test',
 'products': 'DataFrame2',
 'order_payments': 'DataFrame3',
 'geolocation': 'DataFrame4',
 'product_category_name_translation': 'DataFrame5',
 'order_items': 'DataFrame6',
 'orders': 'DataFrame7',
 'order_reviews': 'DataFrame8',
 'sellers': 'DataFrame9'}

In [22]:
test_df = pd.read_csv(os.path.join(csv_path, 'olist_sellers_dataset.csv')).head()
test_df

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [23]:
data['customers'] = pd.read_csv(os.path.join(csv_path, 'olist_sellers_dataset.csv')).head()
data

{'customers':                           seller_id  seller_zip_code_prefix  \
 0  3442f8959a84dea7ee197c632cb2df15                   13023
 1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
 2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
 3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
 4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

          seller_city seller_state
 0           campinas           SP
 1         mogi guacu           SP
 2     rio de janeiro           RJ
 3          sao paulo           SP
 4  braganca paulista           SP  ,
 'products': 'DataFrame2',
 'order_payments': 'DataFrame3',
 'geolocation': 'DataFrame4',
 'product_category_name_translation': 'DataFrame5',
 'order_items': 'DataFrame6',
 'orders': 'DataFrame7',
 'order_reviews': 'DataFrame8',
 'sellers': 'DataFrame9'}

In [16]:
from olist.data import Olist
Olist().get_data()['sellers'].head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

❓This piece of code needs to work from anywhere on your machine, not only in this notebook.
- Open a new terminal
- Go to your home folder `cd`
- Launch an `ipython` session
- Test the two lines of code above

In [ ]:
## avant training enlever les id