Data source : https://www.kaggle.com/c/home-credit-default-risk/data

But notebook : Test API

Lancement API locale :

  - aller dans le dossier /app_API
  - make build
  - make run

# Imports

In [1]:
import requests
import os
import pickle
import pandas as pd

# Tests points d'entrée

## /data

In [4]:
# Créer le répertoire s'il n'existe pas
output_dir = "../data/api_output"
os.makedirs(output_dir, exist_ok=True)

In [5]:
# Format parquet
response = requests.get("http://127.0.0.1:8000/data?format=parquet")

# Afficher les 100 premiers octets pour un aperçu
preview = response.content[:100]
print("Aperçu des données Parquet :", preview)

# Écrire le contenu complet dans un fichier dans le répertoire spécifique
parquet_output_path = os.path.join(output_dir, "data.parquet")
with open(parquet_output_path, "wb") as f:
    f.write(response.content)

Aperçu des données Parquet : b'PAR1\x15\x04\x15\xb8\xb4Q\x15\x80\xb5QL\x15\x8e\xad\x14\x15\x00\x12\x00\x00\x9c\xda(\xf4\xff\xffPd\x18?\xae!(?\xb0s\x89>\xd8\x02-?\xc4i\x14?\x02\x94\x14?0\xc1\x17?\xb9\xf1+?F\x939?\xd6\xf4 ?\xc6\xe3\x17?\xde=\x10;|z.?\x1dp\xa1>\xc5\x10\xbe>\xc9\xbeF?\x02_4?q\x00'

In [6]:
df = pd.read_parquet(parquet_output_path)
df.shape

(210118, 38)

In [7]:
df.head()

,EXT_SOURCE_2,EXT_SOURCE_3,PAYMENT_RATE,INSTAL_DPD_MEAN,INSTAL_AMT_PAYMENT_SUM,AMT_ANNUITY,DAYS_BIRTH,CODE_GENDER,ANNUITY_INCOME_PERC,APPROVED_AMT_DOWN_PAYMENT_MAX,...,PREV_APP_CREDIT_PERC_MIN,APPROVED_DAYS_DECISION_MIN,INSTAL_AMT_PAYMENT_MEAN,INSTAL_DBD_SUM,INSTAL_AMT_INSTALMENT_MAX,INCOME_CREDIT_PERC,INSTAL_DAYS_ENTRY_PAYMENT_MEAN,INSTAL_PAYMENT_DIFF_MEAN,SK_ID_CURR,TARGET
0,0.595281,0.706205,0.039660,0.461538,7.992843e+05,53541.0,-16961,1,0.198300,90000.0,...,1.137779,-2208.0,61483.410156,295.0,66693.781250,0.200000,-2021.538452,5050.211426,442623,0.0
1,0.656764,0.071055,0.032398,4.256757,2.602840e+06,30033.0,-12187,1,0.222467,14931.0,...,0.824513,-2604.0,35173.523438,897.0,922513.062500,0.145631,-1484.216187,8585.831055,164728,0.0
2,0.268461,0.256706,0.047191,0.125000,3.242952e+05,10737.0,-15445,0,0.119300,22441.5,...,1.111116,-2289.0,13512.297852,113.0,13531.634766,0.395570,-1916.583374,0.000000,136291,0.0
3,0.675825,0.355639,0.067940,0.000000,6.519330e+04,30573.0,-13321,0,0.104523,4500.0,...,1.000000,-2473.0,5926.663574,157.0,7696.529785,0.650000,-2305.454590,0.000000,190853,0.0
4,0.579739,0.363945,0.029348,0.000000,5.055732e+05,34578.0,-19486,0,0.284593,45000.0,...,0.884721,-1049.0,25278.662109,289.0,190605.640625,0.103122,-559.349976,0.000000,198244,0.0

In [25]:
df.columns

Index(['EXT_SOURCE_2', 'EXT_SOURCE_3', 'PAYMENT_RATE', 'INSTAL_DPD_MEAN',
       'INSTAL_AMT_PAYMENT_SUM', 'AMT_ANNUITY', 'DAYS_BIRTH', 'CODE_GENDER',
       'ANNUITY_INCOME_PERC', 'APPROVED_AMT_DOWN_PAYMENT_MAX',
       'DAYS_EMPLOYED_PERC', 'BURO_DAYS_CREDIT_MEAN', 'PREV_CNT_PAYMENT_MEAN',
       'AMT_GOODS_PRICE', 'BURO_AMT_CREDIT_SUM_DEBT_MEAN',
       'ACTIVE_DAYS_CREDIT_MAX', 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN',
       'PREV_APP_CREDIT_PERC_MEAN', 'INSTAL_PAYMENT_PERC_MEAN',
       'NAME_EDUCATION_TYPE_Highereducation', 'DAYS_ID_PUBLISH',
       'APPROVED_CNT_PAYMENT_MEAN', 'BURO_DAYS_CREDIT_MAX',
       'INSTAL_AMT_PAYMENT_MIN', 'INSTAL_DAYS_ENTRY_PAYMENT_SUM',
       'POS_MONTHS_BALANCE_SIZE', 'PREV_NAME_CONTRACT_STATUS_Refused_MEAN',
       'DAYS_REGISTRATION', 'PREV_APP_CREDIT_PERC_MIN',
       'APPROVED_DAYS_DECISION_MIN', 'INSTAL_AMT_PAYMENT_MEAN',
       'INSTAL_DBD_SUM', 'INSTAL_AMT_INSTALMENT_MAX', 'INCOME_CREDIT_PERC',
       'INSTAL_DAYS_ENTRY_PAYMENT_MEAN', 'INSTAL_PAYMENT_DIFF_MEAN',
       'SK_ID_CURR', 'TARGET'],
      dtype='object')

In [8]:
# Format CSV
response = requests.get("http://127.0.0.1:8000/data?format=csv")

# Afficher les 100 premiers octets pour un aperçu
preview = response.content[:100]
print("Aperçu des données CSV :", preview.decode('utf-8'))  # Décoder en chaîne de caractères pour CSV

# Écrire le contenu complet dans un fichier dans le répertoire spécifique
csv_output_path = os.path.join(output_dir, "data.csv")
with open(csv_output_path, "wb") as f:
    f.write(response.content)

Aperçu des données CSV : EXT_SOURCE_2,EXT_SOURCE_3,PAYMENT_RATE,INSTAL_DPD_MEAN,INSTAL_AMT_PAYMENT_SUM,AMT_ANNUITY,DAYS_BIRTH

## /data_test

In [9]:
# Format parquet
response = requests.get("http://127.0.0.1:8000/data_test?format=parquet")

# Afficher les 100 premiers octets pour un aperçu
preview = response.content[:100]
print("Aperçu des données Parquet :", preview)

# Écrire le contenu complet dans un fichier dans le répertoire spécifique
test_parquet_output_path = os.path.join(output_dir, "data_test.parquet")
with open(test_parquet_output_path, "wb") as f:
    f.write(response.content)

Aperçu des données Parquet : b'PAR1\x15\x04\x15\xa8\xfe\x06\x15\xb4\xfe\x06L\x15\xca\xdf\x01\x15\x00\x12\x00\x00\x94\xbf\x03\xf4\x93\xdf\xca&J?\xe0S\x95>2z\x02?\xbc\xef\x1c?\xb7\x0cO?\x0f\xc3\xe3>\xf9\x94\xc9>\x7f\xa8\xf0>\xe9^\x8a>G5/?/\x91"?\x9a\t\xc0>\x86/I?\xba\xbb\x1b?a\xf2>?\x17\x92\x01?\xf3\x17,?\x99\xcd'

In [10]:
df_test = pd.read_parquet(test_parquet_output_path)
df_test.shape

(15588, 38)

In [11]:
df_test.head()

,EXT_SOURCE_2,EXT_SOURCE_3,EXT_SOURCE_1,PAYMENT_RATE,INSTAL_DPD_MEAN,INSTAL_AMT_PAYMENT_SUM,AMT_ANNUITY,DAYS_BIRTH,CODE_GENDER,ANNUITY_INCOME_PERC,...,DAYS_REGISTRATION,PREV_APP_CREDIT_PERC_MIN,APPROVED_DAYS_DECISION_MIN,INSTAL_AMT_PAYMENT_MEAN,INSTAL_DBD_SUM,INSTAL_AMT_INSTALMENT_MAX,INCOME_CREDIT_PERC,INSTAL_DAYS_ENTRY_PAYMENT_MEAN,INSTAL_PAYMENT_DIFF_MEAN,SK_ID_CURR
307507,0.789654,0.159520,0.752614,0.036147,1.571429,41195.925781,20560.5,-19241,1,0.152300,...,-5170.0,1.044079,-1740.0,5885.132324,62.0,17397.900391,0.237342,-2195.000000,0.00000,100001
307508,0.291656,0.432962,0.564990,0.077973,0.111111,56161.843750,17370.0,-18064,0,0.175455,...,-9118.0,1.111173,-757.0,6240.205078,213.0,17656.244141,0.444409,-609.555542,0.00000,100005
307510,0.509677,0.612704,0.525734,0.031123,0.265487,492310.656250,49018.5,-13976,1,0.155614,...,-2000.0,0.000000,-1805.0,4356.731445,369.0,38988.539062,0.200000,-858.548645,622.55072,100028
307514,0.613033,0.312365,0.565290,0.079000,0.000000,90726.750000,14220.0,-9516,0,0.085405,...,-5063.0,1.428571,-1182.0,18145.349609,68.0,18150.705078,0.925000,-1104.599976,0.00000,100065
307515,0.808788,0.522697,0.718507,0.079358,0.000000,462151.968750,28957.5,-12744,1,0.091929,...,-1686.0,0.825628,-829.0,10270.043945,427.0,21199.544922,0.863260,-392.688904,0.00000,100066

## /user_data

In [12]:
user_id = {"SK_ID_CURR": 442623}
response = requests.post("http://127.0.0.1:8000/user_data", json=user_id)
print(response.json())

[{'EXT_SOURCE_2': 0.595280647277832, 'EXT_SOURCE_3': 0.7062051296234131, 'PAYMENT_RATE': 0.039659999310970306, 'INSTAL_DPD_MEAN': 0.4615384638309479, 'INSTAL_AMT_PAYMENT_SUM': 799284.3125, 'AMT_ANNUITY': 53541.0, 'DAYS_BIRTH': -16961, 'CODE_GENDER': 1, 'ANNUITY_INCOME_PERC': 0.19830000400543213, 'APPROVED_AMT_DOWN_PAYMENT_MAX': 90000.0, 'DAYS_EMPLOYED_PERC': 0.24149519205093384, 'BURO_DAYS_CREDIT_MEAN': -1695.3333740234375, 'PREV_CNT_PAYMENT_MEAN': 12.0, 'AMT_GOODS_PRICE': 1350000.0, 'BURO_AMT_CREDIT_SUM_DEBT_MEAN': 3197173.5, 'ACTIVE_DAYS_CREDIT_MAX': -252.0, 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN': 3401.0, 'PREV_APP_CREDIT_PERC_MEAN': 1.1377789974212646, 'INSTAL_PAYMENT_PERC_MEAN': 0.9230769276618958, 'NAME_EDUCATION_TYPE_Highereducation': 1, 'DAYS_ID_PUBLISH': -497, 'APPROVED_CNT_PAYMENT_MEAN': 12.0, 'BURO_DAYS_CREDIT_MAX': -252.0, 'INSTAL_AMT_PAYMENT_MIN': 2652.75, 'INSTAL_DAYS_ENTRY_PAYMENT_SUM': -26280.0, 'POS_MONTHS_BALANCE_SIZE': 12.0, 'PREV_NAME_CONTRACT_STATUS_Refused_MEAN': 0.0, 'DAYS_REGISTRATION': -2108.0, 'PREV_APP_CREDIT_PERC_MIN': 1.1377789974212646, 'APPROVED_DAYS_DECISION_MIN': -2208.0, 'INSTAL_AMT_PAYMENT_MEAN': 61483.41015625, 'INSTAL_DBD_SUM': 295.0, 'INSTAL_AMT_INSTALMENT_MAX': 66693.78125, 'INCOME_CREDIT_PERC': 0.20000000298023224, 'INSTAL_DAYS_ENTRY_PAYMENT_MEAN': -2021.5384521484375, 'INSTAL_PAYMENT_DIFF_MEAN': 5050.21142578125, 'SK_ID_CURR': 442623, 'TARGET': 0.0}]

## /shap

In [13]:
user_id = {"SK_ID_CURR": 442623}
response = requests.post("http://127.0.0.1:8000/shap", json=user_id)

# Afficher la réponse brute
print("Status Code:", response.status_code)
print("Response Content:", response.content)

Status Code: 200
Response Content: b'[[-0.09884810711278333,-0.9087273810548296,-0.4862894508062103,-0.0038103171121508755,-0.5164578030072821,0.2787360971885895,0.21096897889990812,-0.41697294025361276,0.07246233215172414,-0.40851885085710987,-0.1829500406128059,-0.4326394508588534,-0.09713726458832095,-0.9069609235551122,-0.5325417567285784,0.02442001880829064,0.07732741274793546,-0.058288799930034024,-0.4768370469975532,-0.6946742617880585,-0.6446111853859515,-0.7086948206957202,-0.030530575596624886,0.27450849519330084,-0.04313259911460158,-0.23734111456000198,-0.6012613081655561,-0.1353336282413134,-0.20283993674459985,-0.15306459661968594,-0.2277443102768239,-0.04677080289382549,-0.11666147591623267,-0.2689067479248998,-0.21361183709045709,0.01603975892331572]]'

## /predict

### Vérification features modèle

In [185]:
# Charger le modèle
with open('../app_API/app/model.pkl', 'rb') as file:
    model = pickle.load(file)

# Afficher le nombre de caractéristiques attendu par le modèle
print(f"Number of features expected by the model: {model.n_features_in_}")

Number of features expected by the model: 36

In [186]:
dir(model)

['_Booster',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_is_fitted__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_base_doc',
 '_best_iteration',
 '_best_score',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_class_map',
 '_class_weight',
 '_classes',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_evals_result',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_le',
 '_more_tags',
 '_n_classes',
 '_n_features',
 '_n_features_in',
 '_objective',
 '_other_params',
 '_process_n_jobs',
 '_process_params',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_validate_data',
 '_validate_params',
 'best_iteration_',
 'best_score_',
 'booster_',
 'boosting_type',
 'class_weight',
 'classes_',
 'colsample_bytree',
 'evals_result_',
 'feature_importances_',
 'feature_name_',
 'fit',
 'fitted_',
 'get_metadata_routing',
 'get_params',
 'importance_type',
 'learning_rate',
 'max_depth',
 'min_child_samples',
 'min_child_weight',
 'min_split_gain',
 'n_classes_',
 'n_estimators',
 'n_estimators_',
 'n_features_',
 'n_features_in_',
 'n_iter_',
 'n_jobs',
 'num_leaves',
 'objective',
 'objective_',
 'predict',
 'predict_proba',
 'random_state',
 'reg_alpha',
 'reg_lambda',
 'score',
 'set_fit_request',
 'set_params',
 'set_predict_proba_request',
 'set_predict_request',
 'set_score_request',
 'subsample',
 'subsample_for_bin',
 'subsample_freq']

In [187]:
model.get_params

### Vérification dtypes

In [14]:
import pandas as pd
csv_path_output = '../data/output/'
X_train_filename = 'train_df_cleaned_smote.parquet.gzip'
X_test_filename = 'test_df_cleaned.parquet.gzip'

X_train = pd.read_parquet(csv_path_output + X_train_filename)

In [15]:
X_train.head()

,EXT_SOURCE_2,EXT_SOURCE_3,PAYMENT_RATE,INSTAL_DPD_MEAN,INSTAL_AMT_PAYMENT_SUM,AMT_ANNUITY,DAYS_BIRTH,CODE_GENDER,ANNUITY_INCOME_PERC,APPROVED_AMT_DOWN_PAYMENT_MAX,...,PREV_APP_CREDIT_PERC_MIN,APPROVED_DAYS_DECISION_MIN,INSTAL_AMT_PAYMENT_MEAN,INSTAL_DBD_SUM,INSTAL_AMT_INSTALMENT_MAX,INCOME_CREDIT_PERC,INSTAL_DAYS_ENTRY_PAYMENT_MEAN,INSTAL_PAYMENT_DIFF_MEAN,SK_ID_CURR,TARGET
0,0.595281,0.706205,0.039660,0.461538,7.992843e+05,53541.0,-16961,1,0.198300,90000.0,...,1.137779,-2208.0,61483.410156,295.0,66693.781250,0.200000,-2021.538452,5050.211426,442623,0.0
1,0.656764,0.071055,0.032398,4.256757,2.602840e+06,30033.0,-12187,1,0.222467,14931.0,...,0.824513,-2604.0,35173.523438,897.0,922513.062500,0.145631,-1484.216187,8585.831055,164728,0.0
2,0.268461,0.256706,0.047191,0.125000,3.242952e+05,10737.0,-15445,0,0.119300,22441.5,...,1.111116,-2289.0,13512.297852,113.0,13531.634766,0.395570,-1916.583374,0.000000,136291,0.0
3,0.675825,0.355639,0.067940,0.000000,6.519330e+04,30573.0,-13321,0,0.104523,4500.0,...,1.000000,-2473.0,5926.663574,157.0,7696.529785,0.650000,-2305.454590,0.000000,190853,0.0
4,0.579739,0.363945,0.029348,0.000000,5.055732e+05,34578.0,-19486,0,0.284593,45000.0,...,0.884721,-1049.0,25278.662109,289.0,190605.640625,0.103122,-559.349976,0.000000,198244,0.0

In [16]:
X_train.shape

(210118, 38)

In [17]:
X_train.dtypes

EXT_SOURCE_2                              float32
EXT_SOURCE_3                              float32
PAYMENT_RATE                              float32
INSTAL_DPD_MEAN                           float32
INSTAL_AMT_PAYMENT_SUM                    float32
AMT_ANNUITY                               float32
DAYS_BIRTH                                  int16
CODE_GENDER                                  int8
ANNUITY_INCOME_PERC                       float32
APPROVED_AMT_DOWN_PAYMENT_MAX             float32
DAYS_EMPLOYED_PERC                        float32
BURO_DAYS_CREDIT_MEAN                     float32
PREV_CNT_PAYMENT_MEAN                     float32
AMT_GOODS_PRICE                           float32
BURO_AMT_CREDIT_SUM_DEBT_MEAN             float32
ACTIVE_DAYS_CREDIT_MAX                    float32
ACTIVE_DAYS_CREDIT_ENDDATE_MEAN           float32
PREV_APP_CREDIT_PERC_MEAN                 float32
INSTAL_PAYMENT_PERC_MEAN                  float32
NAME_EDUCATION_TYPE_Highereducation          int8
DAYS_ID_PUBLISH                             int16
APPROVED_CNT_PAYMENT_MEAN                 float32
BURO_DAYS_CREDIT_MAX                      float32
INSTAL_AMT_PAYMENT_MIN                    float32
INSTAL_DAYS_ENTRY_PAYMENT_SUM             float32
POS_MONTHS_BALANCE_SIZE                   float32
PREV_NAME_CONTRACT_STATUS_Refused_MEAN    float32
DAYS_REGISTRATION                         float32
PREV_APP_CREDIT_PERC_MIN                  float32
APPROVED_DAYS_DECISION_MIN                float32
INSTAL_AMT_PAYMENT_MEAN                   float32
INSTAL_DBD_SUM                            float32
INSTAL_AMT_INSTALMENT_MAX                 float32
INCOME_CREDIT_PERC                        float32
INSTAL_DAYS_ENTRY_PAYMENT_MEAN            float32
INSTAL_PAYMENT_DIFF_MEAN                  float32
SK_ID_CURR                                  int32
TARGET                                    float32
dtype: object

### Query API

In [18]:
# query mock data
query_data = {
    "EXT_SOURCE_2": 0.1,
    "EXT_SOURCE_3": 0.2,
    "PAYMENT_RATE": 0.5,
    "INSTAL_DPD_MEAN": 0.0,
    "INSTAL_AMT_PAYMENT_SUM": 10000.0,
    "AMT_ANNUITY": 10000.0,
    "DAYS_BIRTH": -10000,
    "CODE_GENDER": 0.0,
    "ANNUITY_INCOME_PERC": 0.1,
    "APPROVED_AMT_DOWN_PAYMENT_MAX": 10000.0,
    "DAYS_EMPLOYED_PERC": 0.1,
    "BURO_DAYS_CREDIT_MEAN": -1000,
    "PREV_CNT_PAYMENT_MEAN": 10.0,
    "AMT_GOODS_PRICE": 100000.0,
    "BURO_AMT_CREDIT_SUM_DEBT_MEAN": 10000.0,
    "ACTIVE_DAYS_CREDIT_MAX": -1000,
    "ACTIVE_DAYS_CREDIT_ENDDATE_MEAN": -1000,
    "PREV_APP_CREDIT_PERC_MEAN": 0.1,
    "INSTAL_PAYMENT_PERC_MEAN": 0.1,
    "NAME_EDUCATION_TYPE_Highereducation": 1.0,
    "DAYS_ID_PUBLISH": -1000,
    "APPROVED_CNT_PAYMENT_MEAN": 10.0,
    "BURO_DAYS_CREDIT_MAX": -1000,
    "INSTAL_AMT_PAYMENT_MIN": 10000.0,
    "INSTAL_DAYS_ENTRY_PAYMENT_SUM": -1000,
    "POS_MONTHS_BALANCE_SIZE": 10.0,
    "PREV_NAME_CONTRACT_STATUS_Refused_MEAN": 0.0,
    "DAYS_REGISTRATION": -1000,
    "PREV_APP_CREDIT_PERC_MIN": 0.1,
    "APPROVED_DAYS_DECISION_MIN": -1000,
    "INSTAL_AMT_PAYMENT_MEAN": 10000.0,
    "INSTAL_DBD_SUM": 0.0,
    "INSTAL_AMT_INSTALMENT_MAX": 10000.0,
    "INCOME_CREDIT_PERC": 0.1,
    "INSTAL_DAYS_ENTRY_PAYMENT_MEAN": -1000,
    "INSTAL_PAYMENT_DIFF_MEAN": 0.0
}

response = requests.post("http://127.0.0.1:8000/predict", json=query_data)

# Afficher la réponse brute
print("Status Code:", response.status_code)
print("Response Content:", response.content)

Status Code: 200
Response Content: b'{"prediction":[1.0]}'

In [19]:
len(query_data)

36

In [20]:
# query predict with user fetched data
user_id = {"SK_ID_CURR": 442623}
user_info = requests.post("http://127.0.0.1:8000/user_data", json=user_id)
user_data = user_info.json()
print(user_data)

[{'EXT_SOURCE_2': 0.595280647277832, 'EXT_SOURCE_3': 0.7062051296234131, 'PAYMENT_RATE': 0.039659999310970306, 'INSTAL_DPD_MEAN': 0.4615384638309479, 'INSTAL_AMT_PAYMENT_SUM': 799284.3125, 'AMT_ANNUITY': 53541.0, 'DAYS_BIRTH': -16961, 'CODE_GENDER': 1, 'ANNUITY_INCOME_PERC': 0.19830000400543213, 'APPROVED_AMT_DOWN_PAYMENT_MAX': 90000.0, 'DAYS_EMPLOYED_PERC': 0.24149519205093384, 'BURO_DAYS_CREDIT_MEAN': -1695.3333740234375, 'PREV_CNT_PAYMENT_MEAN': 12.0, 'AMT_GOODS_PRICE': 1350000.0, 'BURO_AMT_CREDIT_SUM_DEBT_MEAN': 3197173.5, 'ACTIVE_DAYS_CREDIT_MAX': -252.0, 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN': 3401.0, 'PREV_APP_CREDIT_PERC_MEAN': 1.1377789974212646, 'INSTAL_PAYMENT_PERC_MEAN': 0.9230769276618958, 'NAME_EDUCATION_TYPE_Highereducation': 1, 'DAYS_ID_PUBLISH': -497, 'APPROVED_CNT_PAYMENT_MEAN': 12.0, 'BURO_DAYS_CREDIT_MAX': -252.0, 'INSTAL_AMT_PAYMENT_MIN': 2652.75, 'INSTAL_DAYS_ENTRY_PAYMENT_SUM': -26280.0, 'POS_MONTHS_BALANCE_SIZE': 12.0, 'PREV_NAME_CONTRACT_STATUS_Refused_MEAN': 0.0, 'DAYS_REGISTRATION': -2108.0, 'PREV_APP_CREDIT_PERC_MIN': 1.1377789974212646, 'APPROVED_DAYS_DECISION_MIN': -2208.0, 'INSTAL_AMT_PAYMENT_MEAN': 61483.41015625, 'INSTAL_DBD_SUM': 295.0, 'INSTAL_AMT_INSTALMENT_MAX': 66693.78125, 'INCOME_CREDIT_PERC': 0.20000000298023224, 'INSTAL_DAYS_ENTRY_PAYMENT_MEAN': -2021.5384521484375, 'INSTAL_PAYMENT_DIFF_MEAN': 5050.21142578125, 'SK_ID_CURR': 442623, 'TARGET': 0.0}]

In [21]:
user_data = user_data[0]

In [22]:
if "TARGET" in user_data:
    user_data.pop("TARGET")

if "SK_ID_CURR" in user_data:
    user_data.pop("SK_ID_CURR")

In [23]:
user_data

{'EXT_SOURCE_2': 0.595280647277832,
 'EXT_SOURCE_3': 0.7062051296234131,
 'PAYMENT_RATE': 0.039659999310970306,
 'INSTAL_DPD_MEAN': 0.4615384638309479,
 'INSTAL_AMT_PAYMENT_SUM': 799284.3125,
 'AMT_ANNUITY': 53541.0,
 'DAYS_BIRTH': -16961,
 'CODE_GENDER': 1,
 'ANNUITY_INCOME_PERC': 0.19830000400543213,
 'APPROVED_AMT_DOWN_PAYMENT_MAX': 90000.0,
 'DAYS_EMPLOYED_PERC': 0.24149519205093384,
 'BURO_DAYS_CREDIT_MEAN': -1695.3333740234375,
 'PREV_CNT_PAYMENT_MEAN': 12.0,
 'AMT_GOODS_PRICE': 1350000.0,
 'BURO_AMT_CREDIT_SUM_DEBT_MEAN': 3197173.5,
 'ACTIVE_DAYS_CREDIT_MAX': -252.0,
 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN': 3401.0,
 'PREV_APP_CREDIT_PERC_MEAN': 1.1377789974212646,
 'INSTAL_PAYMENT_PERC_MEAN': 0.9230769276618958,
 'NAME_EDUCATION_TYPE_Highereducation': 1,
 'DAYS_ID_PUBLISH': -497,
 'APPROVED_CNT_PAYMENT_MEAN': 12.0,
 'BURO_DAYS_CREDIT_MAX': -252.0,
 'INSTAL_AMT_PAYMENT_MIN': 2652.75,
 'INSTAL_DAYS_ENTRY_PAYMENT_SUM': -26280.0,
 'POS_MONTHS_BALANCE_SIZE': 12.0,
 'PREV_NAME_CONTRACT_STATUS_Refused_MEAN': 0.0,
 'DAYS_REGISTRATION': -2108.0,
 'PREV_APP_CREDIT_PERC_MIN': 1.1377789974212646,
 'APPROVED_DAYS_DECISION_MIN': -2208.0,
 'INSTAL_AMT_PAYMENT_MEAN': 61483.41015625,
 'INSTAL_DBD_SUM': 295.0,
 'INSTAL_AMT_INSTALMENT_MAX': 66693.78125,
 'INCOME_CREDIT_PERC': 0.20000000298023224,
 'INSTAL_DAYS_ENTRY_PAYMENT_MEAN': -2021.5384521484375,
 'INSTAL_PAYMENT_DIFF_MEAN': 5050.21142578125}

In [24]:
response = requests.post("http://127.0.0.1:8000/predict", json=user_data)
# Afficher la réponse brute
print("Status Code:", response.status_code)
print("Response Content:", response.content)

Status Code: 200
Response Content: b'{"prediction":[0.0]}'